### ISSUE TITLE
SyntaxError: f-string: expecting '}' on line 75 and 107

### ISSUE THREAD

**Issue by Viddesh1** [TechBroAdedara/TicTacToe-with-FastHTML#1]
Thanks @TechBroAdedara for creating this repository using fasthtml. I had fun playing the game.

While running the main.py using python3 main.py i encounter below error:
```
    return f"this: {"X" if num == "O" else "O"}"
                     ^
SyntaxError: f-string: expecting '}'
```

There was conflit between " " and ' ' while returning the value.

Please find my fix below:

line 75: return f'Player {"X" if player == "O" else "O"}\'s turn!'
line 107: f'{text if text is not None else "." }'

**Comment by TechBroAdedara** [comment]
Oh, I think that issue was already fixed some time ago. The original code has the same fix you just mentioned. 
All should work well now. Thanks for letting me know. And please notify me if there is any other issue.
